config/routes.rb
AssocApp::Application.routes.draw do
  root :to => 'customers#index'

  resources :customers do
    resources :orders do
      resources :items
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include CustomersHelper
  attr_accessible :contact, :name, :phone

  has_many :orders

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  include OrdersHelper

  attr_accessible :cost, :name, :quantity, :customer_id, :item_id, :customer_name

  belongs_to :customer
  has_one :item

  before_validation :convert_customer_name_to_id
  validates :customer_id, :presence => {:message => "Customer name must be provided and match exiting customer"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Customer.find(params[:customer_id]).orders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    params[:order] = params[:order].except(:customer_name)
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    params[:order] = params[:order].except(:customer_name)
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper

    # From http://stackoverflow.com/a/11483295
    def table_builder(columns, collection = {})
        thead = content_tag :thead do
            content_tag :tr do
                columns.collect {|column|  concat content_tag(:th,column[:display_name])}.join().html_safe
            end
        end

        tbody = content_tag :tbody do
            collection.collect { |elem|
            content_tag :tr do
                columns.collect { |column|
                concat content_tag(:td, elem.attributes[column[:name]])
                }.to_s.html_safe
            end
            }.join().html_safe
        end
        content_tag :table, thead.concat(tbody), class: "table"
    end

end

app/helpers/orders_helper.rb
module OrdersHelper

    def convert_customer_name_to_id
        customer = Customer.find_by_name(self.customer_name(self))
        self.customer_id = customer.id unless customer.nil?
    end

    def customer_name(order)
        order.customer.name unless order.customer.nil?
    end

    def table_builder(orders)
        table = ""
        table += "<table class=\"table\">"
        table += "<tr>"
        table += "<th>Quantity</th>"
        table += "<th>Name</th>"
        table += "<th>Cost</th>"
        table += "<th></th>"
        table += "<th></th>"
        table += "<th></th>"
        table += "</tr>"
        orders.each do |order|
            table += "<tr>"
            table += "<td>#{order.quantity}</td>"
            table += "<td>#{order.name}</td>"
            table += "<td>#{order.cost}</td>"
            table += "<td>" + link_to('Show', customer_order_path(order.customer, order)) + "</td>"
            table += "<td>" + link_to('Edit', edit_customer_order_path(order.customer, order)) + "</td>"
            table += "<td>" + link_to('Destroy', customer_order_path(order.customer, order), method: :delete, data: { confirm: 'Are you sure?' }) + "</td>"
            table += "</tr>"
        end
        return table += "</table>"
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Contact</th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.phone %></td>
    <td><%= customer.contact %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Place Order', new_customer_order_path(customer) %></td>
    <td><%= link_to 'View Orders', customer_orders_path(customer) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Contact:</b>
  <%= @customer.contact %>
</p>




<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssocApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
    <div class="span12">
        <%= yield %>
    </div>
</div>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Order for: <%= Customer.find(params[:customer_id]).name %></p>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  
  <div class="field">
    <%= f.label :name_list %><br />
    <%= f.collection_select :item_id, Item.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <%= f.hidden_field :customer_name, :value => Customer.find(params[:customer_id]).name %>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<%= table_builder(@orders).html_safe %>

<br />

<%= link_to 'New Order', new_customer_order_path(params[:customer_id]) %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>

<p>
  <b>Name:</b>
  <%= @order.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @order.cost %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>